### ISSUE TITLE
Error : urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by politicus** [loris/alfred-producthunt-workflow#2]
Just got this error as I was trying to use the workflow : 

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "ph.py", line 11, in get_items
    data = json.loads(urllib2.urlopen(request).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

Is it API related or I do not have the right dependencies installed? 
I've checked node.js is installed  (v. 0.10.33)

**Comment by loris** [comment]
Strange, that kind of HTTP error (`403`) should not be occuring since `v1.1`. The workflow is now not hitting the Product Hunt API directly but using a node proxy.
Can you check in your `ph.py` file that you are correctly using the proxy server which is located at `https://alfred-producthunt-workflow.herokuapp.com/v1/posts`?
Anyway you don't need any dependecy or node.js installed on your own machine.

**Comment by politicus** [comment]
Reinstalled the workflow from github. Working fine.
If I remember well, I think I have tried to solve my problem by reinstalling the workflow from Packal.org. 
It didn't work. Maybe the versions are different?
